name: infyners
description: INFYNERS - Batch notices & routines
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_fonts: ^6.2.1
  fluttertoast: ^9.0.0
  flutter_local_notifications: ^19.5.0
  firebase_messaging: ^15.1.0
  timezone: ^0.10.1
  intl: ^0.19.0
  iconsax: ^0.0.8
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  pdf: ^3.11.1
  printing: ^5.13.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: false
