name: batch_notice_app
description: Batch-only notices & routines
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_fonts: ^6.2.1
  fluttertoast: ^9.0.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  iconsax: ^0.0.8
  font_awesome_flutter: ^10.7.0

flutter:
  uses-material-design: true
